# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  pull_request:
    branches: ["dev"]

permissions:
  contents: read

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: petching.net
  CODE_DEPLOY_APPLICATION_NAME: petching-CodeDeploy
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: petching-CodeDeploy-group

jobs:
  build:
    runs-on: ubuntu-latest
    
    # 작업 공간
    env:
      working-directory: ./server
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    # AWS Access 권한 확인
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        
    # 권한 추가
    - name: Add permission
      run: chmod +x gradlew
      working-directory: ${{ env.working-directory }}
      
    # 빌드
    - name: Build with Gradle
      run: ./gradlew clean build
      working-directory: ${{ env.working-directory }}
    
    # 빌드한 프로젝트 압축
    - name: Make project zip file
      run: zip -r ./petching.zip .
      shell: bash
    
    
    # 압축한 프로젝트를 S3로 전송
    - name: Upload to AWS S3
      run: aws s3 cp --region ap-northeast-2 ./petching.zip s3://$S3_BUCKET_NAME/petching.zip
      
    # CodeDeploy를 통한 배포
    - name: Code Deploy
      run: >
        aws deploy create-deployment --application-name $CODE_DEPLOY_APPLICATION_NAME
        --deployment-config-name CodeDeployDefault.AllAtOnce
        --deployment-group-name $CODE_DEPLOY_DEPLOYMENT_GROUP_NAME
        --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=petching.zip
